export const en = {
  addNote: 'Add new note',
  title: 'Title',
  text: 'Text',
  owner: 'Owner',
  tags: 'Tags',
  type: 'Type',
  deleteNote: 'Delete',
  editNote: 'Edit',
  header: 'Adding a note',
  submit: 'Submit',
  cancel: 'Cancel',
  form: 'Registration form',
  name: 'Name',
  surname: 'Surname',
  password: 'Password',
  private: 'Private',
  public: 'Public',
  color: 'color',
  regester: 'Regestration form',
  yourName: 'Enter your name',
  yourSurname: 'Enter your surname',
  yourPassword: 'Enter your password',
  wantToDelete: 'Are you sure to delete?',
  wantToEdit: 'Edit a note',
  removeFavourites: 'Remove from favorites',
  addFavourites: 'Add to favorite',
  publicNotes: 'Public notes',
  goPublic: 'Go to public notes',
  changePassword: 'Change password',
  addNewPassword: 'Enter a new password',
  ok: "Okey",
  newPassword: 'You have successfully changed your password',
  goPrivate: 'Go to private notes',
  logout: 'LogOut',
  removedFavourites: 'The note was removed from favorites!',
  addedFavourites: 'The note was added to favorites!',
  readMore:'Read more...'
}
