export const ru = {
  addNote: 'Добавить заметку',
  title: 'Заголовок',
  text: 'Текст',
  owner: 'Владелец',
  tags: 'Теги',
  type: 'Тип заметки',
  deleteNote: 'Удалить',
  editNote: 'Редактировать',
  header: 'Добавить заметку',
  submit: 'Отправить',
  cancel: 'Отменить',
  form: 'Форма регистрации',
  name: 'Имя',
  surname: 'Фамилия',
  password: 'Пароль',
  private: 'Приватный',
  public: 'Публичный',
  color: 'Цвет',
  regester: 'Форма регистрации',
  yourName: 'Введите свое имя',
  yourSurname: 'Введите свою фамилию',
  yourPassword: 'Введите свой пароль',
  wantToDelete: 'Вы уверены, что хотите удалить?',
  wantToEdit: 'Редактирование заметки',
  removeFavourites: 'Удалить из избранного',
  addFavourites: 'Добавить в избранное',
  publicNotes: 'Публичные заметки',
  goPublic: 'Перейти к публичным заметкам',
  changePassword: 'Поменять пароль',
  addNewPassword: 'Введите новый пароль',
  ok: 'Хорошо',
  newPassword: 'Вы успешно сменили пароль!',
  goPrivate: 'Перейти к приватным заметкам',
  logout: 'Выйти',
  removedFavourites: 'Заметка удалена из избранного!',
  addedFavourites: 'Заметка добавлена в избранное!',
  readMore: 'Подробнее...',
  favourite: "Избранное"
}
